install:
    - sudo add-apt-repository -y ppa:texlive-backports/ppa
    - sudo apt-get update
    - sudo apt-get install -y texlive-latex-extra
    - sudo apt-get install -y texlive-luatex
    - sudo apt-get install -y texlive-fonts-extra
    - sudo apt-get install -y texlive-bibtex-extra
    - sudo apt-get install -y latexmk

script:
    - make once

deploy:
  provider: releases
  api_key: "76fd9afc59f262c96405f9c1bd5b01fec6b07b96"
  file: "main.pdf"
  skip_cleanup: true
  on:
    tags: true
