install:
    - sudo add-apt-repository -y ppa:texlive-backports/ppa
    - sudo apt-get update
    - sudo apt-get install -y texlive-latex-extra
    - sudo apt-get install -y texlive-luatex
    - sudo apt-get install -y texlive-fonts-extra
    - sudo apt-get install -y texlive-bibtex-extra
    - sudo apt-get install -y latexmk

script:
    - make once

deploy:
  provider: releases
  api_key: "3b4f7e9a389a1948cad51879205630f887c63724"
  file: "main.pdf"
  skip_cleanup: true
  on:
    tags: true
